stages:
  - build
  - test
  - deploy

variables:
  DOCKER_IMAGE_BACKEND: $CI_REGISTRY_IMAGE/backend:$CI_COMMIT_REF_SLUG
  DOCKER_IMAGE_STREAMLIT: $CI_REGISTRY_IMAGE/streamlit:$CI_COMMIT_REF_SLUG

services:
  - docker:27-dind

build:
  stage: build
  image: docker:27
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build --pull -t $DOCKER_IMAGE_BACKEND -f docker/Dockerfile .
    - docker push $DOCKER_IMAGE_BACKEND
    - docker build --pull -t $DOCKER_IMAGE_STREAMLIT -f docker/Dockerfile .
    - docker push $DOCKER_IMAGE_STREAMLIT
  only:
    - main

test_backend:
  stage: test
  image: $DOCKER_IMAGE_BACKEND
  script:
    - cd /app
    - PYTHONPATH=. pytest tests/
  only:
    - main
    - merge_requests
  allow_failure: true

test_frontend:
  stage: test
  image: node:20-slim
  script:
    - cd frontend
    - npm install --prefer-offline --no-audit
    - npm run lint || echo "Linting failed but continuing..."
  only:
    - main
    - merge_requests
  allow_failure: true

deploy:
  stage: deploy
  image: ubuntu:latest
  before_script:
    - apt-get update -y && apt-get install -y openssh-client
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - eval $(ssh-agent -s)
    - >
      if [ -z "$AWS_PRIVATE_KEY" ]; then
      echo "CRITICAL ERROR: AWS_PRIVATE_KEY is not defined!";
      exit 1;
      fi
    - >
      if [ -f "$AWS_PRIVATE_KEY" ]; then
      tr -d '\r' < "$AWS_PRIVATE_KEY" > ~/.ssh/id_rsa;
      else
      printf "%s\n" "$AWS_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa;
      fi
    - chmod 600 ~/.ssh/id_rsa
    - ssh-add ~/.ssh/id_rsa
    - ssh-keyscan $AWS_PUBLIC_IP >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - echo "DOCKER_IMAGE_BACKEND=$DOCKER_IMAGE_BACKEND" > .env
    - echo "DOCKER_IMAGE_STREAMLIT=$DOCKER_IMAGE_STREAMLIT" >> .env
    - scp docker/docker-compose.yml .env $AWS_USERNAME@$AWS_PUBLIC_IP:~/
    - ssh $AWS_USERNAME@$AWS_PUBLIC_IP "
        sudo docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY &&
        sudo docker pull $DOCKER_IMAGE_BACKEND &&
        sudo docker pull $DOCKER_IMAGE_STREAMLIT &&
        sudo docker-compose up -d
      "
  environment:
    name: production
    url: http://$AWS_PUBLIC_IP
  only:
    - main
  when: manual
